ALTER TABLE KHOA ADD CONSTRAINT UN_KHOA_TENKHOA UNIQUE(TENKHOA)

ALTER TABLE LOP ADD CONSTRAINT UN_LOP_TENLOP UNIQUE(TENLOP)

ALTER TABLE MONHOC ADD CONSTRAINT UN_MONHOC_TENMH UNIQUE(TENMH)

ALTER TABLE LOPTINCHI ADD CONSTRAINT CK_LOPTINCHI_HOCKY CHECK ([HOCKY]>=(1) AND [HOCKY]<=(4))

ALTER TABLE LOPTINCHI ADD CONSTRAINT CK_NHOM CHECK ([NHOM]>=(1))

ALTER TABLE DANGKY ADD CONSTRAINT CK_DIEM_CC CHECK ([DIEM_CC]>=(0) AND [DIEM_CC]<=(10))

ALTER TABLE DANGKY ADD CONSTRAINT CK_DIEM_GK CHECK ([DIEM_GK]>=(0) AND [DIEM_GK]<=(10))

ALTER TABLE DANGKY ADD CONSTRAINT CK_DIEM_CK CHECK ([DIEM_CK]>=(0) AND [DIEM_CK]<=(10))
