create PROCEDURE [dbo].[SP_CHECK_EXIST_CREDITCLASS] @Nienkhoa nchar(9),
@Hocky int,
@MaMH nchar(10),
@Nhom int
AS 
BEGIN 
	 IF EXISTS(SELECT * FROM LINK1.QLDSV_TC.dbo.LOPTINCHI AS LOPTC WHERE LOPTC.MAMH = @MaMH 
	 AND LOPTC.NHOM = @Nhom AND LOPTC.NIENKHOA = @Nienkhoa AND LOPTC.HOCKY = @Hocky)
		RETURN 1; --Mã NV tồn tại ở phân mãnh khác
	RETURN 0; 
END
GO

CREATE PROC [dbo].[SP_CHECK_TUITON_SV]
@MASV NCHAR(10), @NIENKHOA NCHAR(9), @HOCKY INT
AS
BEGIN
	DECLARE @TONGTIENDONG INT
	SELECT @TONGTIENDONG=SUM(DHP.SOTIENDONG) FROM LINK0.QLDSV_TC.DBO.CT_DONGHOCPHI DHP 
	WHERE DHP.MASV=@MASV AND DHP.NIENKHOA=@NIENKHOA AND DHP.HOCKY=@HOCKY 
	GROUP BY DHP.SOTIENDONG

	IF EXISTS(SELECT MASV FROM LINK0.QLDSV_TC.DBO.HOCPHI WHERE MASV=@MASV AND NIENKHOA=@NIENKHOA AND HOCKY=@HOCKY AND HOCPHI=@TONGTIENDONG)
	BEGIN
		RETURN 1
	END
	RETURN 0
END
GO

CREATE PROCEDURE [dbo].[SP_CHECKID]
@Ma NVARCHAR(15),
@Type NVARCHAR(15)
AS
BEGIN
	-- LOP
	IF(@Type = 'MALOP')
	BEGIN
	 IF EXISTS(SELECT * FROM LINK1.QLDSV_TC.dbo.LOP AS LOP WHERE LOP.MALOP = @Ma)
		RETURN 1; --Mã NV tồn tại ở phân mãnh khác
	END

	 --MON HOC
	IF(@Type = 'MAMONHOC')
	BEGIN
		IF EXISTS(SELECT * FROM dbo.MONHOC WHERE MAMH = @Ma)
		RETURN 1;
	END

	 --SINH VIEN
	IF(@Type = 'MASV')
	BEGIN
	 IF EXISTS(SELECT * FROM LINK1.QLDSV_TC.dbo.SINHVIEN AS SV WHERE SV.MASV = @Ma)
		RETURN 1; --Mã tồn tại ở phân mãnh khác
	END

	 RETURN 0 --Không bị trùng được thêm
END

GO


CREATE PROCEDURE [dbo].[SP_CHECKNAME]
@Name NVARCHAR(200),
@Type NVARCHAR(50)
AS
BEGIN
	--Kiểm tra Table lop của server hiện tại
	IF(@Type = 'TENLOP')
	BEGIN
	 IF EXISTS(SELECT * FROM LINK1.QLDSV_TC.dbo.LOP AS LOP WHERE LOP.TENLOP = @Name)
		RETURN 1; --KIEM TRA TREN SITE KHAC
	END

	IF(@Type = 'TENMONHOC')
	BEGIN
		IF EXISTS(SELECT * FROM dbo.MONHOC WHERE TENMH = @Name)
		RETURN 1;
	END
	RETURN 0
END
GO


CREATE PROC [dbo].[SP_DANGNHAP]
@TENLOGIN NVARCHAR (50)
AS
BEGIN
	DECLARE @TENUSER NVARCHAR(50)
	SELECT @TENUSER=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)
	SELECT USERNAME = @TENUSER,
		HOTEN = (SELECT HO+ ' '+ TEN FROM GIANGVIEN WHERE MAGV = @TENUSER ),
		TENNHOM= NAME
			FROM sys.sysusers
				WHERE UID = (SELECT GROUPUID
					FROM SYS.SYSMEMBERS
						WHERE MEMBERUID= (SELECT UID FROM sys.sysusers
							WHERE NAME=@TENUSER))
END

GO


CREATE PROC [dbo].[SP_DELETE_DKY_SV]
@MALTC INT, @MASV NCHAR(10), @CHIPHI INT
AS
BEGIN
	DECLARE @NIENKHOA NCHAR(9), @HOCKY INT
	SELECT @NIENKHOA=LTC.NIENKHOA, @HOCKY=LTC.HOCKY FROM LOPTINCHI LTC WHERE LTC.MALTC=@MALTC

	--KIỂM TRA SINH VIÊN ĐÃ ĐÓNG HỌC PHÍ CHƯA
	IF EXISTS(SELECT * FROM LINK2.QLDSV_TC.DBO.CT_DONGHOCPHI CT WHERE CT.MASV=@MASV AND CT.NIENKHOA=@NIENKHOA AND CT.HOCKY=@HOCKY)
	BEGIN
		RAISERROR ('Sinh viên đã hết thời hạn hủy đăng ký',16,1)--NẾU CÓ THÌ KO CHO HỦY ĐK
		RETURN
	END
	
	SET XACT_ABORT ON 
	BEGIN DISTRIBUTED TRANSACTION;

	--CẬP NHẬP TRẠNG THÁI ĐĂNG KÝ 
	UPDATE DANGKY SET HUYDANGKY=1 WHERE DANGKY.MASV=@MASV AND DANGKY.MALTC=@MALTC

	--TÍNH LẠI TỔNG HỌC PHÍ TRONG HỌC KỲ VÀ NIÊN KHÓA ĐÓ
	DECLARE @TONGTIET INT, @HOCPHI INT
	SELECT @TONGTIET=MONHOC.SOTIET_LT+MONHOC.SOTIET_TH 
	FROM (SELECT MAMH FROM LOPTINCHI WHERE MALTC=@MALTC) LTC, MONHOC WHERE LTC.MAMH=MONHOC.MAMH 

	---------lấy kết quả tính được của tổng học phí sau khi hủy đk--------------
	SET @HOCPHI=(SELECT HP.HOCPHI FROM LINK2.QLDSV_TC.DBO.HOCPHI HP WHERE HP.MASV=@MASV AND HP.NIENKHOA=@NIENKHOA AND HP.HOCKY=@HOCKY)-(@TONGTIET/15)*@CHIPHI
	---------nếu tính lại mà học phí vẫn >0 |--> sinh viên vẫn còn có môn đk trong niên khóa và học kỳ đó--> cập nhập lại tiền thui--------------
	IF @HOCPHI>0
	BEGIN
		UPDATE LINK2.QLDSV_TC.DBO.HOCPHI SET HOCPHI-=(@TONGTIET/15)*@CHIPHI WHERE MASV=@MASV AND NIENKHOA=@NIENKHOA AND HOCKY=@HOCKY
	END
	---------ngược lại |--> sinh viên không còn có môn đk nào --->xóa lun --------------
	ELSE
	BEGIN
		DELETE FROM LINK2.QLDSV_TC.DBO.HOCPHI WHERE MASV=@MASV AND NIENKHOA=@NIENKHOA AND HOCKY=@HOCKY
	END
	COMMIT TRANSACTION;
END

GO


CREATE PROC [dbo].[SP_DKY_LOPTINCHI]
@MALTC int , @MASV nchar(10), @CHIPHI INT
AS
BEGIN
	DECLARE @NIENKHOA NCHAR(9), @HOCKY INT, @MAMH NCHAR(10)
	SELECT @NIENKHOA=LTC.NIENKHOA, @HOCKY=LTC.HOCKY, @MAMH=LTC.MAMH FROM LOPTINCHI LTC WHERE LTC.MALTC=@MALTC

	IF EXISTS(SELECT * FROM (SELECT MALTC FROM DANGKY WHERE MASV=@MASV AND HUYDANGKY=0) DK, 
							(SELECT MALTC FROM LOPTINCHI WHERE MAMH=@MAMH AND NIENKHOA=@NIENKHOA AND HOCKY=@HOCKY) LTC
							 WHERE  DK.MALTC=LTC.MALTC)
	BEGIN
		RAISERROR('Sinh viên đã đăng ký lớp này',16,1)
		RETURN
	END

	ELSE IF EXISTS(SELECT * FROM LINK2.QLDSV_TC.DBO.CT_DONGHOCPHI WHERE MASV=@MASV AND NIENKHOA=@NIENKHOA AND HOCKY=@HOCKY)
	BEGIN
		RAISERROR('Sinh viên đã hết thời hạn đăng ký',16,1)
		RETURN
	END
	
	SET XACT_ABORT ON 
	BEGIN DISTRIBUTED TRANSACTION;
	-------------------------------- UPDATE DANGKY === ------------------------------------------------.
	IF EXISTS(SELECT * FROM DANGKY DK WHERE DK.MASV=@MASV AND DK.MALTC=@MALTC AND DK.HUYDANGKY=1)
	BEGIN
		UPDATE DANGKY SET HUYDANGKY=0 WHERE MASV=@MASV AND MALTC=@MALTC 
	END
	ELSE
	BEGIN
		INSERT INTO DANGKY(MALTC, MASV) VALUES (@MALTC, @MASV)
	END

	-------------------- Update HOC PHI SAU KHI DKY from remote instance.--------------------------------
	DECLARE @TONGTIET INT

	SELECT @TONGTIET=MONHOC.SOTIET_LT+MONHOC.SOTIET_TH 
	FROM (SELECT MAMH FROM LOPTINCHI WHERE MALTC=@MALTC) LTC, MONHOC WHERE LTC.MAMH=MONHOC.MAMH 

	--neu da co thong tin hoc phi thi cong them hoc phi
	IF EXISTS(SELECT * FROM LINK2.QLDSV_TC.DBO.HOCPHI HP WHERE HP.MASV=@MASV AND HP.NIENKHOA=@NIENKHOA AND HP.HOCKY=@HOCKY)
	BEGIN
		UPDATE LINK2.QLDSV_TC.DBO.HOCPHI SET HOCPHI+=(@TONGTIET/15)*@CHIPHI WHERE MASV=@MASV AND NIENKHOA=@NIENKHOA AND HOCKY=@HOCKY
	END

	--nguoc lai, them thong tin hoc phi moi cho sinh vien
	ELSE
	BEGIN
		INSERT INTO LINK2.QLDSV_TC.DBO.HOCPHI(MASV,NIENKHOA,HOCKY,HOCPHI) VALUES (@MASV, @NIENKHOA, @HOCKY, (@TONGTIET/15)*@CHIPHI)
	END
	COMMIT TRANSACTION;

	
END

GO

CREATE PROC [dbo].[SP_DS_DKY_SV]
@MASV NCHAR(10), @NIENKHOA NCHAR(9), @HOCKY INT, @CHIPHI INT
AS
BEGIN
	SELECT LTC.MALTC, LTC.MAMH, MONHOC.TENMH, LTC.NHOM, TTH=MONHOC.SOTIET_TH, STC=(MONHOC.SOTIET_LT+MONHOC.SOTIET_TH)/15, HOCPHI=((MONHOC.SOTIET_LT+MONHOC.SOTIET_TH)/15)*@CHIPHI
	 FROM (SELECT * FROM DANGKY WHERE MASV=@MASV AND HUYDANGKY=0) DK, 
			(SELECT * FROM LOPTINCHI WHERE NIENKHOA=@NIENKHOA AND HOCKY=@HOCKY) LTC,
			 MONHOC 
		WHERE DK.MALTC=LTC.MALTC AND LTC.MAMH=MONHOC.MAMH
END

GO

CREATE PROC [dbo].[SP_LOAD_LIST_SCORES]--nienKhoa, hocKy, monHoc, nhom
@NIENKHOA NCHAR(9), @HOCKY INT, @MAMH NCHAR(10), @NHOM INT
AS
BEGIN 
	--maSV, hoten, diem cc, diem gk, diem ck, diem het mon || làm ơn đồng bộ đi mà
	SELECT LTC.MALTC, SV.MASV, HOTEN=HO+' '+TEN, DIEM_CC, DIEM_GK, DIEM_CK, 
	TOPAY= ( SELECT COUNT(MASV) FROM LINK2.QLDSV_TC.DBO.HOCPHI 
			WHERE MASV=SV.MASV AND NIENKHOA=@NIENKHOA AND HOCKY=@HOCKY AND HOCPHI=(SELECT SUM(DHP.SOTIENDONG) FROM LINK2.QLDSV_TC.DBO.CT_DONGHOCPHI DHP
										WHERE DHP.MASV=SV.MASV AND DHP.NIENKHOA=@NIENKHOA AND DHP.HOCKY=@HOCKY 
										GROUP BY DHP.MASV) GROUP BY MASV )			
	FROM (SELECT * FROM LOPTINCHI WHERE NIENKHOA=@NIENKHOA AND HOCKY=@HOCKY AND MAMH=@MAMH AND NHOM=@NHOM) LTC,
			(SELECT * FROM DANGKY WHERE HUYDANGKY=0) DK,  SINHVIEN SV 
	WHERE DK.MASV=SV.MASV  AND DK.MALTC=LTC.MALTC
END
GO

CREATE PROCEDURE [dbo].[SP_LOAD_REGISTER_INFOR] @NIENKHOA CHAR(9), @HOCKY INT
AS
BEGIN
	--MAMH, TENMH, nhóm, Hoten GV gi?ng, , s? sv ?ã ??ng ký;
	SELECT LTC.MALTC, dbo.MONHOC.MAMH, dbo.MONHOC.TENMH, LTC.NHOM,  dbo.GIANGVIEN.HO + ' ' + dbo.GIANGVIEN.TEN AS HOTEN
	,SOSV=IsNULL((SELECT COUNT(DK.MALTC) FROM DANGKY DK WHERE DK.HUYDANGKY=0 AND DK.MALTC=LTC.MALTC GROUP BY DK.MALTC), 0)
	FROM (SELECT * FROM LOPTINCHI WHERE NIENKHOA=@NIENKHOA AND HOCKY=@HOCKY AND HUYLOP=0  ) LTC,
	 MONHOC, GIANGVIEN 
	WHERE MONHOC.MAMH = LTC.MAMH AND GIANGVIEN.MAGV = LTC.MAGV
END

GO


CREATE PROC [dbo].[SP_LOGIN_SV]
@TENLOGIN NVARCHAR (50), @MASV NCHAR(10), @PASS NVARCHAR(40)
AS
BEGIN
	IF EXISTS(SELECT * FROM SINHVIEN SV WHERE SV.MASV=@MASV AND SV.PASSWORD=@PASS)
	BEGIN
		DECLARE @TENUSER NVARCHAR(50)
		SELECT @TENUSER=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)

		SELECT MASV=@MASV, HOTEN=(SELECT HO+ ' '+ TEN FROM SINHVIEN WHERE MASV = @MASV ),
			TENNHOM=(SELECT NAME
			FROM sys.sysusers
				WHERE UID = (SELECT GROUPUID
					FROM SYS.SYSMEMBERS
						WHERE MEMBERUID= (SELECT UID FROM sys.sysusers
							WHERE NAME=@TENUSER)))
	END
END


GO

create proc [dbo].[SP_PAY_TUITION_MONEY]
@Ma nchar(10),
@Nienkhoa nchar(9),
@Hocky int,
@Ngaydong datetime,
@Sotiendong int
AS
BEGIN
	insert into CT_DONGHOCPHI(MASV,NIENKHOA,HOCKY,NGAYDONG,SOTIENDONG) values(@Ma,@Nienkhoa,@Hocky,@Ngaydong,@Sotiendong)
END
GO

CREATE proc [dbo].[SP_PAY_TUITIONFEE]
@Ma nchar(10)
as
begin
select hp.MASV,hp.NIENKHOA, hp.HOCKY,hp.HOCPHI ,
 PADED=isnull((select SUM(cthp.SOTIENDONG)),0) 
from	(SELECT * FROM HOCPHI WHERE HOCPHI.MASV = @Ma) hp LEFT JOIN
		(SELECT * FROM CT_DONGHOCPHI WHERE CT_DONGHOCPHI.MASV = @Ma) cthp
		ON (hp.NIENKHOA = cthp.NIENKHOA AND hp.HOCKY = cthp.HOCKY)
group by hp.MASV, hp.NIENKHOA,hp.HOCKY,hp.HOCPHI
order by hp.NIENKHOA,hp.HOCKY asc
end

GO

CREATE PROC [dbo].[SP_REPORT_CLASS_SCORES]
@MALOP NCHAR(10)
AS
BEGIN
	SELECT DK.MASV, HOTEN, MAMH, DIEM= MAX(DIEM_CC*0.1+DIEM_GK*0.3+DIEM_CK*0.6) 
	FROM  (SELECT MASV, HOTEN=HO+' '+TEN FROM SINHVIEN WHERE MALOP=@MALOP) SV,
					DANGKY DK, (SELECT MALTC, LOPTINCHI.MAMH, TENMH FROM LOPTINCHI, MONHOC WHERE LOPTINCHI.MAMH=MONHOC.MAMH) LTC
	WHERE DK.MASV=SV.MASV AND DK.MALTC=LTC.MALTC
	GROUP BY DK.MASV, HOTEN, MAMH
	ORDER BY DK.MASV
END
GO

CREATE PROC [dbo].[SP_REPORT_CREDIT_CLASS_SCORES]
@NIENKHOA NCHAR(9), @HOCKY INT, @MAMH NCHAR(10), @NHOM INT
AS
BEGIN
	DECLARE @MALTC INT 
	SELECT @MALTC= MALTC FROM LOPTINCHI WHERE HUYLOP=0 AND NIENKHOA=@NIENKHOA AND HOCKY=@HOCKY AND MAMH=@MAMH AND NHOM=@NHOM
	
	SELECT DK.MASV, HO, TEN, DIEM_CC, DIEM_GK, DIEM_CK FROM  (SELECT * FROM DANGKY WHERE MALTC=@MALTC) DK, (SELECT MASV, HO,TEN FROM SINHVIEN) SV
	WHERE DK.MASV=SV.MASV
	ORDER BY TEN,HO
END
GO

CREATE proc [dbo].[SP_REPORT_LOPTINCHI]
@Nienkhoa nchar(9),
@Hocky int
as
BEGIN
	SELECT MONHOC= (SELECT mh.TENMH FROM MONHOC mh WHERE mh.MAMH = ltc.MAMH),
	ltc.NHOM,GIANGVIEN= (SELECT gv.HO+' '+gv.TEN FROM GIANGVIEN gv WHERE gv.MAGV=ltc.MAGV),
	ltc.SOSVTOITHIEU, SVDANGKY = (select COUNT(*) from DANGKY dk where dk.MALTC = ltc.MALTC)
	FROM (SELECT * FROM LOPTINCHI WHERE LOPTINCHI.NIENKHOA = @Nienkhoa and LOPTINCHI.HOCKY = @Hocky and LOPTINCHI.HUYLOP = 0 ) ltc
END

GO


CREATE proc [dbo].[SP_REPORT_STUDENTLIST_CREDITCLASS]
@Nienkhoa nchar(9),
@Hocky int, 
@Mamonhoc nchar(10),
@Nhom int
as
DECLARE @Maloptinchi int
BEGIN
	SELECT @Maloptinchi = ltc.MALTC FROM LOPTINCHI ltc WHERE 
	ltc.MAMH = @Mamonhoc and  ltc.NHOM = @Nhom and ltc.NIENKHOA = @Nienkhoa and ltc.HOCKY = @Hocky 

	SELECT SINHVIEN.MASV,SINHVIEN.HO,SINHVIEN.TEN,SINHVIEN.PHAI,SINHVIEN.MALOP
	FROM (select DANGKY.MASV FROM DANGKY WHERE DANGKY.MALTC = @Maloptinchi) SVDANGKY, SINHVIEN 
	WHERE SINHVIEN.MASV = SVDANGKY.MASV
	ORDER BY SINHVIEN.TEN,SINHVIEN.HO,SINHVIEN.MASV
END

GO


CREATE PROC [dbo].[SP_REPORT_SV_SCORES]
@MASV NCHAR(10)
AS
--MÃ MH, TÊN MÔN HỌC, ĐIỂM CC, GK , CK.
BEGIN
	SELECT LTC.MAMH, TENMH, DIEMKT=MAX(DIEM_CC*0.1+DIEM_GK*0.3+DIEM_CK*0.6)
	FROM (SELECT * FROM DANGKY WHERE  MASV=@MASV AND HUYDANGKY=0 ) DK, 
		(SELECT MALTC, MAMH FROM LOPTINCHI) LTC,
		MONHOC MH
	WHERE DK.MALTC=LTC.MALTC AND LTC.MAMH=MH.MAMH
	GROUP BY LTC.MAMH, TENMH
	ORDER BY TENMH
END

GO

create proc [dbo].[SP_REPORT_TUITIONFEE]
@Malop nchar(10),
@Nienkhoa nchar(9),
@Hocky int
as
begin 
	select SV.MASV, HOTEN=SV.HO+' '+SV.TEN,HP.HOCPHI,CT.SOTIENDADONG
	from (select MASV,HO,TEN from SINHVIEN where MALOP=@MALOP) as SV	
	left join 
	(select MASV,HOCPHI FROM HOCPHI Where NIENKHOA = @NIENKHOA and HOCKY=@HOCKY) as HP
	ON HP.MASV=SV.MASV
	left join
	(select MASV,SOTIENDADONG=SUM(SOTIENDONG) FROM CT_DONGHOCPHI WHERE NIENKHOA = @NIENKHOA and HOCKY=@HOCKY GROUP BY MASV) as CT
	ON HP.MASV=CT.MASV
end


GO

CREATE procedure [dbo].[SP_SHOW_DETAIL_TUITIONFEE] 
@Ma nchar(10),
@Nienkhoa nchar(9),
@Hocky int
AS
BEGIN
	Select ct.NGAYDONG,ct.SOTIENDONG  from CT_DONGHOCPHI ct
	where ct.MASV = @Ma and ct.NIENKHOA = @Nienkhoa and ct.HOCKY = @Hocky
END
GO

CREATE proc [dbo].[SP_SHOW_SUBJECT] @masv nchar(10)
AS
BEGIN
	SELECT dbo.LOPTINCHI.MALTC, dbo.LOPTINCHI.HOCKY, dbo.MONHOC.TENMH, dbo.GIANGVIEN.HO + ' ' + dbo.GIANGVIEN.TEN AS HOTEN, dbo.LOPTINCHI.NHOM, dbo.LOPTINCHI.SOSVTOITHIEU, dbo.LOPTINCHI.HUYLOP,DaDangKy=IsNULL((SELECT COUNT(MASV) FROM DANGKY DK WHERE MASV=@masv AND DK.MALTC=LOPTINCHI.MALTC GROUP BY MASV), 0)
	FROM dbo.LOPTINCHI INNER JOIN dbo.MONHOC ON dbo.MONHOC.MAMH = dbo.LOPTINCHI.MAMH 
		INNER JOIN dbo.GIANGVIEN ON dbo.GIANGVIEN.MAGV = dbo.LOPTINCHI.MAGV
END

GO

CREATE PROC [dbo].[SP_TAOLOGIN]
  @LGNAME VARCHAR(50),
  @PASS VARCHAR(50),
  @USERNAME VARCHAR(50),
  @ROLE VARCHAR(50)
AS
	if exists(select name from sys.server_principals 
				where type in('U','S','G')
				and name NOT LIKE '%##%'
				and name = @LGNAME)
			return 1 --trùng login--
	else if exists(SELECT name FROM sys.database_principals
					WHERE type_desc = 'SQL_USER'
					AND name = @USERNAME)
			return 2
	EXEC SP_ADDLOGIN @LGNAME, @PASS,'QLDSV_TC'
	EXEC SP_GRANTDBACCESS @LGNAME, @USERNAME

	EXEC sp_addrolemember @ROLE, @USERNAME
	IF @ROLE= 'PGV' OR @ROLE= 'KHOA' OR @ROLE= 'PKT'
	BEGIN 
		EXEC sp_addsrvrolemember @LGNAME, 'SecurityAdmin'
		EXEC sp_addsrvrolemember @LGNAME, 'ProcessAdmin'
	END
RETURN 0  -- THANH CONG

GO

CREATE PROC [dbo].[SP_UPDATE_SCORES]
@MALTC INT, @MASV NCHAR(10), @DIEMCC INT , @DIEMGK FLOAT, @DIEMCK FLOAT
AS
BEGIN
	UPDATE DANGKY SET DIEM_CC=@DIEMCC, DIEM_GK=@DIEMGK, DIEM_CK=@DIEMCK WHERE MALTC=@MALTC AND MASV=@MASV
END
